openapi: 3.0.3

info:
  title: Snapshotter
  description: The alpha implementation of the Snapshotter interface.
  version: 0.0.0

paths:
  /snapshotter/health:
    get:
      summary: Health check endpoint.
      description: Provides an endpoint to check the overall health of the Snapshotter service.
      operationId: GetHealth
      responses:
        200:
          description: Service is healthy.


  /snapshotter/write-snapshot:
    post:
      summary: Write snapshot.
      description: Write snapshot based on bucket/key.
      operationId: PostWriteSnapshot
      parameters:
      - name: bucket
        in: query
        description: bucket containing snapshot key
        required: true
        schema:
          type: string
      - name: key
        in: query
        description: key identifying snapshot
        required: true
        schema:
          type: string
      - name: version
        in: query
        description: bucket/key version
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: byte
      responses:
        200:
          $ref: '#/components/responses/WriteSnapshotResponse'
  
  /snapshotter/read-snapshot:
    get:
      summary: Read snapshot.
      description: Read snapshot based on bucket/key.
      operationId: GetReadSnapshot
      parameters:
      - name: bucket
        in: query
        description: bucket containing snapshot key
        required: true
        schema:
          type: string
      - name: key
        in: query
        description: key identifying snapshot
        required: true
        schema:
          type: string
      - name: version
        in: query
        description: bucket/key version
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              format: byte
      responses:
        200:
          description: Bytes making up the contents of the snapshot.
          content:
            text/plain:
              schema:
                type: string
                format: byte

components:
  responses:
    WriteSnapshotResponse:
      description: Placeholder response.
      content:
        application/json:
          schema:
            type: object