openapi: 3.0.3

info:
  title: WriteLogger
  description: The alpha implementation of the WriteLogger interface.
  version: 0.0.0

paths:
  /writelogger/health:
    get:
      summary: Health check endpoint.
      description: Provides an endpoint to check the overall health of the WriteLogger service.
      operationId: GetHealth
      responses:
        200:
          description: Service is healthy.


  /writelogger/append-message:
    post:
      summary: Append message to WriteLogger.
      description: Appends a message to a versioned bucket/key.
      operationId: PostAppendMessage
      requestBody:
        content:
          application/json:
            example:
              bucket: example-bucket
              key: unique-key
              version: 4
              message: SGVsbG8gV29ybGQ=
            schema:
              type: object
              properties:
                bucket:
                  type: string
                key:
                  type: string
                version:
                  type: integer
                  format: int64
                message:
                  type: string
                  format: byte
      responses:
        200:
          $ref: '#/components/responses/AppendMessageResponse'
  
  /writelogger/log-reader:
    post:
      summary: Read log.
      description: Reads an entire log (collection of messages) at bucket/key for the given version.
      operationId: PostLogReader
      requestBody:
        content:
          application/json:
            example:
              bucket: example-bucket
              key: unique-key
              version: 4
            schema:
              type: object
              properties:
                bucket:
                  type: string
                key:
                  type: string
                version:
                  type: integer
                  format: int64
      responses:
        200:
          description: Bytes making up the contents of the log.
          content:
            text/plain:
              schema:
                type: string
                format: byte

  /writelogger/delete-log:
    post:
      summary: Delete log.
      description: Deletes the log at bucket/key for the given version.
      operationId: PostDeleteLog
      requestBody:
        content:
          application/json:
            example:
              bucket: example-bucket
              key: unique-key
              version: 4
            schema:
              type: object
              properties:
                bucket:
                  type: string
                key:
                  type: string
                version:
                  type: integer
                  format: int64
      responses:
        200:
          description: Log was deleted.

components:
  responses:
    AppendMessageResponse:
      description: Placeholder response.
      content:
        application/json:
          schema:
            type: object