// Code generated by "stringer -type=apiMethod"; DO NOT EDIT.

package pilosa

import "strconv"

const _apiMethod_name = "apiClusterMessageapiCreateFieldapiCreateFrameapiCreateIndexapiDeleteFieldapiDeleteFrameapiDeleteIndexapiDeleteViewapiExportCSVapiFieldsapiFragmentBlockDataapiFragmentBlocksapiFrameAttrDiffapiImportapiImportValueapiIndexapiIndexAttrDiffapiMarshalFragmentapiQueryapiRecalculateCachesapiRemoveNodeapiResizeAbortapiRestoreFrameapiSetCoordinatorapiSliceNodesapiUnmarshalFragmentapiViews"

var _apiMethod_index = [...]uint16{0, 17, 31, 45, 59, 73, 87, 101, 114, 126, 135, 155, 172, 188, 197, 211, 219, 235, 253, 261, 281, 294, 308, 323, 340, 353, 373, 381}

func (i apiMethod) String() string {
	if i < 0 || i >= apiMethod(len(_apiMethod_index)-1) {
		return "apiMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _apiMethod_name[_apiMethod_index[i]:_apiMethod_index[i+1]]
}
