version: '3.9'

services:
  featurebase:
    image: docker.io/featurebasedb/featurebase:latest
    ports:
     - "10101:10101"
    volumes:
      - "featurebase:/data"

volumes:
  featurebase:
    driver: local

networks:
  default:
    name: fbnet
    external: true
