# Dockerfile for building a container which can cross compile darwin with cgo
# on linux
# 
# fbsql depends https://github.com/confluentinc/confluent-kafka-go thus
# requiring cgo to build. This generally isn't an issue unless you want to cross
# compile the darwin build on linux. To cross compile darwin build on linux with
# cgo, you need a C cross compiler. This Dockerfile utilizes
# "https://github.com/tpoechtrager/osxcross.git for this. 
#
# In order for osxcross to build compilers, it requires Xcode. Xcode is a
# complete developer toolset for creating apps for Mac, iPhone, etc. The .xip
# file required for this docker files can be founder here:
# https://developer.apple.com/download/all/. Decide which Xcode version you'd
# like to build with AND what version of go you'd like to build with.
#
# For this to work, that Xcode.xip file must be in the working directory. For
# now, you'll need to manually define the version.

FROM ubuntu:focal AS builder

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /
RUN apt-get update -y -qq && apt-get install -y -qq \
  build-essential \
  git \
  musl-tools \
  netcat \
  unixodbc \
  unixodbc-dev \
  clang \
  libxml2-dev \
  liblzma-dev \
  cmake \
  cpio \
  libssl-dev \
  zlib1g-dev \
  libbz2-dev \
  wget \
  libmpc-dev \
  && rm -rf /var/lib/apt/lists/*

# build compilers for cross compilation (darwin on linux) with cgo
WORKDIR /
RUN git clone https://github.com/tpoechtrager/osxcross.git \
 && wget http://192.168.1.212:8000/Xcode_13.4.1.xip \
 && cd /osxcross \
 && ./tools/gen_sdk_package_pbzx.sh /Xcode_13.4.1.xip \
 && mv ./MacOSX12.3.sdk.tar.xz /osxcross/tarballs \
 && rm /Xcode_13.4.1.xip

WORKDIR /osxcross
RUN export UNATTENDED=1 \
 && export PATH=/osxcross/build/cctools-port:$PATH \
 && export PATH=/osxcross/build/cctools-port/cctools:$PATH \
 && export PATH=/osxcross/build/cctools-port/cctools:$PATH \
 && export PATH=/osxcross/build/:$PATH \
 && ./build.sh \