ARG GO_VERSION=latest

######################
### Pilosa builder ###
######################

FROM golang:${GO_VERSION} as pilosa-builder
ARG MAKE_FLAGS
WORKDIR /pilosa

COPY . ./

RUN make build FLAGS="-o build/pilosa" ${MAKE_FLAGS}

FROM moleculacorp/idk as idk
RUN apk add --no-cache bash curl jq 
LABEL maintainer "dev@molecula.com"


COPY --from=pilosa-builder /pilosa/build/pilosa /
COPY testBackupRestore.sh /
CMD ["bash","/testBackupRestore.sh"]
