ARG GO_VERSION=latest

######################
### Pilosa builder ###
######################

FROM golang:${GO_VERSION} as pilosa-builder
ARG MAKE_FLAGS
WORKDIR /pilosa

COPY . ./

RUN make build FLAGS="-o build/pilosa" ${MAKE_FLAGS}

FROM moleculacorp/idk as idk
LABEL maintainer "dev@molecula.com"
RUN apt-get update -y
RUN apt-get install -y bash curl jq


COPY --from=pilosa-builder /pilosa/build/pilosa /
COPY testBackupRestore.sh /
CMD ["bash","/testBackupRestore.sh"]
