package pilosa

const (
	MetricCreateIndex           = "createIndex"
	MetricDeleteIndex           = "deleteIndex"
	MetricCreateField           = "createField"
	MetricDeleteField           = "deleteField"
	MetricDeleteAvailableShard  = "deleteAvailableShard"
	MetricRecalculateCache      = "cache.recalculate"
	MetricInvalidateCache       = "cache.invalidate"
	MetricRankCacheLength       = "RankCache"
	MetricCacheThresholdReached = "cache.threshold"
	MetricRow                   = "range"
	MetricRowBSI                = "range:bsigroup"
	MetricSetRowAttrs           = "SetRowAttrs"
	MetricSetProfileAttrs       = "SetProfileAttrs"
	MetricMaximumRow            = "maximum_row"
	MetricSetBit                = "setBit"
	MetricRows                  = "rows"
	MetricClearBit              = "clearBit"
	MetricSetRow                = "setRow"
	MetricClearRow              = "clearRow"
	MetricImportingN            = "ImportingN"
	MetricImportedN             = "ImportedN"
	MetricClearingN             = "ClearingN"
	MetricClearedN              = "ClearedN"
	MetricSnapshot              = "snapshot"
	MetricBlockRepairPrimary    = "BlockRepairPrimary"
	MetricBlockRepair           = "BlockRepair"
	MetricSyncField             = "syncField"
	MetricSyncIndex             = "syncIndex"
	MetricColumnAttrStoreBlocks = "ColumnAttrStoreBlocks"
	MetricColumnAttrDiff        = "ColumnAttrDiff"
	MetricRowAttrStoreBlocks    = "RowAttrStoreBlocks"
	MetricRowAttrDiff           = "RowAttrDiff"
	MetricHttpRequest           = "http.request"
	MetricMaxShard              = "maxShard"
	MetricAntiEntropy           = "AntiEntropy"
	MetricAntiEntropyDuration   = "AntiEntropyDuration"
	MetricGarbageCollection     = "garbage_collection"
	MetricGoroutines            = "goroutines"
	MetricOpenFiles             = "OpenFiles"
	MetricHeapAlloc             = "HeapAlloc"
	MetricHeapInuse             = "HeapInuse"
	MetricStackInuse            = "StackInuse"
	MetricMallocs               = "Mallocs"
	MetricFrees                 = "Frees"
)
