ARG GO_VERSION=1.19

FROM golang:${GO_VERSION}

WORKDIR /go/src/github.com/featurebasedb/featurebase/

COPY . .

WORKDIR /go/src/github.com/featurebasedb/featurebase/batch/

CMD ["go","test","-v","-mod=vendor","-tags=odbc,dynamic","./..."]
