
resources:
  - name: featurebaseRepo
    type: GitRepo
    configuration:
      # SCM integration where the repository is located
      gitProvider: github_molecula_featurebase
      # Repository path, including org name/repo name
      path: molecula/featurebase
      branches:
        # Specifies which branches will trigger dependent steps
        include: cicd
  - name: featurebaseBuildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: Molecula_Artifactory
      buildName: featurebase_build
      buildNumber: 4
pipelines:
  - name: ScanGoCode
    steps:
      - name: scan
        type: XrayScan
        configuration:
          failOnScan: false
          inputResources:
            - name: featurebaseBuildInfo
              trigger: true
        execution:
          onStart:
            - echo "Preparing for work..."
            - echo "Prepping build environment"
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:
            - echo "Cleaning up some stuff"