---
development:
  dialect: postgres
  database: {{envOr "POSTGRES_DB" "dax_development"}}
  user: {{envOr "POSTGRES_USER" "postgres"}}
  password: {{envOr "POSTGRES_PASSWORD" "testpass"}}
  host: {{envOr "POSTGRES_HOST" "127.0.0.1"}}
  pool: 5

test:
  dialect: postgres
  database: {{envOr "POSTGRES_DB" "dax_test"}}
  user: {{envOr "POSTGRES_USER" "postgres"}}
  password: {{envOr "POSTGRES_PASSWORD" "testpass"}}
  host: {{envOr "POSTGRES_HOST" "127.0.0.1"}}
  pool: 5

production:
  dialect: postgres
  database: {{envOr "POSTGRES_DB" "controller"}}
  user: {{envOr "POSTGRES_USER" "dax"}}
  password: {{envOr "POSTGRES_PASSWORD" ""}}
  host: {{envOr "POSTGRES_HOST" "127.0.0.1"}}
  pool: 10 # TODO
