---
development:
  dialect: postgres
  database: {{envOr "POSTGRES_DATBASE" "dax_development"}}
  user: {{envOr "POSTGRES_USER" "postgres"}}
  password: {{envOr "POSTGRES_PASSWORD" "testpass"}}
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: {{envOr "POSTGRES_DATBASE" "dax_test"}}
  user: {{envOr "POSTGRES_USER" "postgres"}}
  password: {{envOr "POSTGRES_PASSWORD" "testpass"}}
  host: 127.0.0.1
  pool: 5

# production:
#   url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/dax_production?sslmode=disable"}}
