package datagen

var skills = []string{
	"Data Entry",
	"Answering Phones",
	"Billing",
	"Bookkeeping (Excel, Turbotax)",
	"Scheduling",
	"Ms Office",
	"Office Equipment",
	"Quickbooks",
	"Shipping",
	"Welcoming Visitors",
	"Salesforce",
	"Calendar Management",
	"Organization",
	"Time Management",
	"Problem Solving",
	"Attention To Detail",
	"Adaptability",
	"Written Communication",
	"Email Platforms (E.G., Gmail And iCloud Mail)",
	"Word Processing Software (E.G., Google Docs)",
	"Spreadsheet Software",
	"Databases",
	"Digital Calendars",
	"Prioritization",
	"Product Knowledge",
	"Lead Qualification",
	"Lead Prospecting",
	"Customer Needs Analysis",
	"Referral Marketing",
	"Contract Negotiation",
	"Self Motivation",
	"Increasing Customer Lifetime Value (Clv)",
	"Reducing Customer Acquisition Cost (Cac)",
	"CRM Software (Salesforce, Hubspot, Zoho, Freshsales)",
	"POS Skills",
	"Cashier Skills",
	"Problem Solving",
	"Patience",
	"Knowledge Of Products And Services",
	"Adaptability",
	"Customer Service",
	"Communication",
	"Math Skills",
	"Organization",
	"Time Management",
	"Negotiation",
	"Persuasion",
	"Patience",
	"Diplomacy",
	"Cold Calling",
	"Customer Relationship Management (CRM)",
	"Lead Generation",
	"Buyer-responsive Selling",
	"Buyer Engagement",
	"Teamwork",
	"Patient Assessment",
	"Taking Vital Signs",
	"Patient Care",
	"Recording Patient Medical History",
	"Wound Dressing And Care",
	"Urgent And Emergency Care",
	"Record-keeping",
	"Patient Education",
	"NIH Stroke Scale Patient Assessment",
	"Electronic Medical Record (EMR)",
	"Medicine Administration",
	"Blood Pressure Monitoring",
	"Phlebotomy",
	"Rehabilitation Therapy",
	"Hygiene Assistance",
	"Use Of X-ray, MRI, Cat Scans",
	"Meditech",
	"Glucose Checks",
	"Electronic Heart Record (EHR)",
	"Time Management",
	"Prioritization",
	"Decision-Making Ability",
	"Critical Thinking",
	"Leadership",
	"Thorough Understanding Of HIPPA And Privacy Policies",
	"Ability To Take And Record Vital Signs",
	"CPR And First-Aid Certifications",
	"Perform And Evaluate Diagnostic Tests",
	"Maintain Patient Charts",
	"Programming Languages",
	"Web Development",
	"Data Structures",
	"Open Source Experience",
	"Security",
	"Machine Learning",
	"Debugging",
	"UX/UI",
	"Front-End & Back-End Development",
	"Cloud Management",
	"Agile Development",
	"HTML/CSS",
	"CSS Preprocessors",
	"Javascript",
	"Wordpress",
	"Graphic User Interfaces (GUI)",
	"Git/Version Control (Github, gitlab)",
	"Search Engine Optimization (SEO)",
	"Application Programming Interface (API)",
	"Adobe Photoshop, InDesign",
	"Content Management Systems (CMS)",
	"Testing/Debugging",
	"Responsive Design Principles",
	"Mobile and Web Development (e.g. iOS, Android)",
	"STEM Skills",
	"CAD",
	"Design",
	"Prototyping",
	"Testing",
	"Troubleshooting",
	"Project Launch",
	"Lean Manufacturing",
	"Workflow Development",
	"Computer Skills",
	"SolidWorks",
	"Budgeting",
	"Technical Report Writing",
	"Programming Languages HTML, CSS, CRM tools",
	"SEO (SEMRush, WordPress, and Ahrefs)",
	"SEM (i.e., Google Adwords)",
	"PPC",
	"CRO and A/B Testing",
	"Social Media Marketing and Paid Social Media Advertising",
	"Sales Funnel Management",
	"CMS Tools (WordPress, Weebly)",
	"Graphic Design Skills (Adobe Creative Suite)",
	"Email Marketing (MailChimp, Constant Contact)",
	"Email Automation",
	"Data Visualization",
	"CPC",
	"Typography",
	"Print Design",
	"Photography and Branding",
	"Communication",
	"Creativity",
	"Data Analytics (Google Analytics )",
	"Web Analytics",
	"Adaptability",
	"Organized",
	"Email Writing",
	"Google Adwords",
	"Social Media And Mobile Marketing",
	"Paid Social Media Advertisements",
	"Consumer Behavior Drivers",
	"Brand Management",
	"B2b Marketing",
	"Writing Advertising Copy",
	"Soliciting Feedback From Customers",
	"Cutting Costs",
	"Leadership skills",
	"Task Delegation",
	"Strategic Management",
	"Negotiation",
	"Planning",
	"Proposal writing",
	"Problem-solving",
	"Innovation",
	"Charisma",
	"Problem solving",
	"Personable",
	"Website Management",
	"Social Media Outreach",
	"Video Production",
	"Data Visualization",
	"Campaign Management",
	"Photo Editing",
	"Editing",
	"Typography",
	"Logo Creation",
	"Digital Printing",
	"Interactive Media Design",
	"Color Sense & Theory",
	"Ad Design",
	"Social Media Publishing",
	"UX Design",
	"Storytelling",
	"Financial Analysis",
	"Consumer Research",
	"Statistical Analysis",
	"Drawing",
	"Design",
	"Videography",
	"Technical Writing",
	"Mobile and Web Development (e.g. iOS, Android)",
	"Agile Project Management (Kanban)",
	"Managing Cross-Functional Teams",
	"Scrum Management",
	"Performance Tracking",
	"Financial Modelling",
	"Ideation Leadership",
	"Feature Definition",
	"Forecasting",
	"Profit and Loss",
	"Scope Management",
	"Project Lifecycle Management",
	"Meeting Facilitation",
	"Leadership",
	"Communication",
	"Critical Thinking",
	"Time Management",
	"Mentoring",
	"Risk Management",
	"Negotiation",
	"Cost Management",
	"Data Analysis",
	"Collaborative",
	"Collaborative Programs (Slack, WhatsApp, Dropbox)",
	"Wordpress",
	"Adobe Creative Suite",
	"Performance Tracking",
}
