name: CD

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  validate:
    runs_on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: open workspace
        run: cd $GITHUB_WORKSPACE

      - name: lint
        run: golangci-lint run -v --timeout=8m

      - name: go vet
        run: go vet ./...

      # - name: test
      #   run: go test ./...

  release:
    needs: validate
    runs_on: ubuntu-latest
      
    steps:
      - name: go-semantic-release
        uses: go-semantic-release/action@v1.17.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}


  build:
    needs: [validate, release]
    runs_on: ubuntu-latest
    matrix:
      goos: 
        - "darwin"
        - "linux"
        - "windows"
      goarch:
        - "amd64"
        - "arm64"
    
    steps:
      - name: build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./build/${{ matrix.goos }}-${{ matrix.goarch }}

      - name: upload

