name: CD

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  validate:
    runs_on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with: 
          go-version: '^1.19.1'

      - run: go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m

      - name: go vet
        run: go vet ./...

      - name: test
        run: go test ./...

  build:
    needs: validate
    runs_on: ubuntu-latest
    matrix:
      goos: 
        - "darwin"
        - "linux"
        - "windows"
      goarch:
        - "amd64"
        - "arm64"
    
    steps:
      - name: build
        run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./build/${{ matrix.goos }}-${{ matrix.goarch }}

      # - name: upload artifacts
      #   uses: upload artifacts

  release:
    needs: [validate, build]
    runs_on: ubuntu-latest
      
    steps:
      - name: go-semantic-release
        uses: go-semantic-release/action@v1.17.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry: true