name: Release

on: 
  push:
    branches:
      - 'chore/gh2181/release-builds'
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo $(git describe --tags)
      - run: |
          current=$(git describe --tags | grep -Eo '[0-9]*?\.[0-9]*?\.[0-9]*')
          array=($(echo $current | tr '.' '\n'))
          array[2]=$((array[2]+1))
          echo "version=$(IFS="." ; echo "${array[*]}")" >> $GITHUB_OUTPUT

  build-lattice:
    runs-on: ubuntu-latest
    env:
        CI: false
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - run: |
          cd lattice
          yarn install
          yarn build
          mv build ../
          cd ../
          rm -r lattice
          mv build lattice
          tar -czvf lattice.tar.gz lattice

      - uses: actions/upload-artifact@v3
        with:
          name: lattice.tar.gz
          path: ./lattice.tar.gz

  build-featurebase:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos:
          - "darwin"
          - "linux"
        goarch:
          - "amd64"
          - "arm64"

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19.1"

      - name: build featurebase
        run: |
          go build -o ./build/featurebase-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/featurebase
          go build -o ./build/roaring-migrate-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/roaring-migrate

      - uses: actions/upload-artifact@v3
        with:
          name: featurebase-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./build/featurebase-${{ matrix.goos }}-${{ matrix.goarch }}

      - uses: actions/upload-artifact@v3
        with:
          name: roaring-migrate-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./build/roaring-migrate-${{ matrix.goos }}-${{ matrix.goarch }}

  build-ingest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - "darwin"
          - "linux"
        goarch:
          - "amd64"
          - "arm64"

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19.1"

      - name: build ingester
        run: go build -o ./build/ingester-${{ matrix.goos }}-${{ matrix.goarch }} ./idk/cmd/ingester

      - name: build consumer-csv
        run: go build -o ./build/consumer-csv-${{ matrix.goos }}-${{ matrix.goarch }} ./idk/cmd/molecula-consumer-csv
      
      - name: build consumer-kafka-static
        run: go build -o ./build/consumer-kafka-static-${{ matrix.goos }}-${{ matrix.goarch }} ./idk/cmd/molecula-consumer-kafka-static

      - name: build consumer-sql
        run: go build -o ./build/consumer-sql-${{ matrix.goos }}-${{ matrix.goarch }} ./idk/cmd/molecula-consumer-sql

      - name: build consumer-github
        run: go build -o ./build/consumer-github-${{ matrix.goos }}-${{ matrix.goarch }} ./idk/cmd/molecula-consumer-github

      - name: build consumer-kinesis
        run: go build -o ./build/consumer-kinesis-${{ matrix.goos }}-${{ matrix.goarch }} ./idk/cmd/molecula-consumer-kinesis
      
      - uses: actions/upload-artifact@v3
        with:
          name: ingester-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./build/ingester-${{ matrix.goos }}-${{ matrix.goarch }}

      - uses: actions/upload-artifact@v3
        with:
          name: consumers-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./build/consumer*